name: Build & Integration tests

on:
  push:
    branches:
      - main
      - initial-implementation
  workflow_dispatch:

concurrency:
  group: release-build-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: 3.13.1

jobs:
  unit-test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v.2.10.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true
          architecture: x64

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Flutter lint
        run: |
          flutter analyze
          # lint check the example project
          cd example && flutter analyze

      - name: Run unit tests
        run: flutter test test

  # job responsible for running Flutter tests on iOS devices
  ios-integration-test:
    name: ios-integration-test
    runs-on: macos-13
    timeout-minutes: 30
    strategy:
      matrix:
        device:
          - "iPhone 14 Simulator (16.2)" # the name of the simulator could be different depending on the macos version you are using
      fail-fast: true
    steps:
      - name: "List all simulators"
        run: "xcrun xctrace list devices"
      - name: "Start Simulator"
        # the command "xcrun simctl boot" expects a device identifier
        # the assignment of the UDID variable consists of retrieving the ID of the simulator
        # by extracting it from the command "xcrun xctrace list devices"
        run: |
          UDID=$(xcrun xctrace list devices | grep -m 1 "^${{ matrix.device }}" | awk '{gsub(/[()]/,""); print $NF}')
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - uses: actions/checkout@v3
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v.2.10.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true
          architecture: x64

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run iOS integration tests
        run: |
          cd example
          flutter test --dart-define=API_KEY=${{ secrets.BKT_API_KEY }} --dart-define=API_ENDPOINT=${{ secrets.BKT_API_ENDPOINT }} integration_test

  # job responsible for running Flutter tests on Android devices
  android-integration-test:
    name: android-integration-test
    runs-on: macos-13
    timeout-minutes: 30
    strategy:
      matrix:
        api-level:
          - 33
      fail-fast: true
    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v.2.10.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true
          architecture: x64

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run Android integration tests
        # more info on https://github.com/ReactiveCircus/android-emulator-runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          avd-name: macOS-avd-x64-33
          arch: x86_64
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          channel: stable
          profile: Nexus 6
          script: cd example && flutter test --dart-define=API_KEY=${{ secrets.BKT_API_KEY }} --dart-define=API_ENDPOINT=${{ secrets.BKT_API_ENDPOINT }} integration_test

  build-example-app-android:
    runs-on: macos-13
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v.2.10.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true
          architecture: x64

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build the example app
        run: |
          make build-android

  build-example-app-ios:
    runs-on: macos-13
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v.2.10.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true
          architecture: x64

      - name: Build the example app
        run: |
          make build-ios
